[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
single_vault_program = "12i6Bo93TrMuSmk9cMiVT1yt1P2hcE8hkB92EWe6YnS5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/solana_projects/vaultifi_organization/single-vault-program/keypairs/Lzy1MnsQTNJXKMWtBsVHZruWEjR3HuFCVAQ1mYQTPVr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
